services:
  pages:
    image: jekyll/jekyll:pages
    command: |
      bash -c "
        gem install webrick &&
        jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
